import 'package:bookbuzz/data/models/suggested_book.dart';
import 'package:bookbuzz/static_db/books_list.dart';
import 'package:bookbuzz/static_db/users_list.dart';

class SuggestedBookList {
  static List usersList = UsersList.list;
  // static List booksList = BooksList.list;

  // static List<SuggestedBook> list = [
  //   SuggestedBook(
  //     booksList[0].category,
  //     booksList[0].title,
  //     booksList[0].author,
  //     booksList[0].description,
  //     booksList[0].rating,
  //     booksList[0].ratingCount,
  //     booksList[0].pages,
  //     booksList[0].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3], usersList[7]],
  //     usersList[0],
  //   ),
  //   SuggestedBook(
  //     booksList[1].category,
  //     booksList[1].title,
  //     booksList[1].author,
  //     booksList[1].description,
  //     booksList[1].rating,
  //     booksList[1].ratingCount,
  //     booksList[1].pages,
  //     booksList[1].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3], usersList[7]],
  //     usersList[1],
  //   ),
  //   SuggestedBook(
  //     booksList[2].category,
  //     booksList[2].title,
  //     booksList[2].author,
  //     booksList[2].description,
  //     booksList[2].rating,
  //     booksList[2].ratingCount,
  //     booksList[2].pages,
  //     booksList[2].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3], usersList[7]],
  //     usersList[2],
  //   ),
  //   SuggestedBook(
  //     booksList[3].category,
  //     booksList[3].title,
  //     booksList[3].author,
  //     booksList[3].description,
  //     booksList[3].rating,
  //     booksList[3].ratingCount,
  //     booksList[3].pages,
  //     booksList[3].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3], usersList[7]],
  //     usersList[3],
  //   ),
  //   SuggestedBook(
  //     booksList[4].category,
  //     booksList[4].title,
  //     booksList[4].author,
  //     booksList[4].description,
  //     booksList[4].rating,
  //     booksList[4].ratingCount,
  //     booksList[4].pages,
  //     booksList[4].coverImgUrl,
  //     [usersList[0], usersList[2], usersList[3], usersList[7]],
  //     usersList[4],
  //   ),
  //   SuggestedBook(
  //     booksList[5].category,
  //     booksList[5].title,
  //     booksList[5].author,
  //     booksList[5].description,
  //     booksList[5].rating,
  //     booksList[5].ratingCount,
  //     booksList[5].pages,
  //     booksList[5].coverImgUrl,
  //     [usersList[0], usersList[2], usersList[3]],
  //     usersList[5],
  //   ),
  //   SuggestedBook(
  //     booksList[6].category,
  //     booksList[6].title,
  //     booksList[6].author,
  //     booksList[6].description,
  //     booksList[6].rating,
  //     booksList[6].ratingCount,
  //     booksList[6].pages,
  //     booksList[6].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3]],
  //     usersList[6],
  //   ),
  //   SuggestedBook(
  //     booksList[7].category,
  //     booksList[7].title,
  //     booksList[7].author,
  //     booksList[7].description,
  //     booksList[7].rating,
  //     booksList[7].ratingCount,
  //     booksList[7].pages,
  //     booksList[7].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3]],
  //     usersList[0],
  //   ),
  //   SuggestedBook(
  //     booksList[8].category,
  //     booksList[8].title,
  //     booksList[8].author,
  //     booksList[8].description,
  //     booksList[8].rating,
  //     booksList[8].ratingCount,
  //     booksList[8].pages,
  //     booksList[8].coverImgUrl,
  //     [usersList[0], usersList[1], usersList[2], usersList[3], usersList[7]],
  //     usersList[8],
  //   ),
  //   SuggestedBook(
  //     booksList[9].category,
  //     booksList[9].title,
  //     booksList[9].author,
  //     booksList[9].description,
  //     booksList[9].rating,
  //     booksList[9].ratingCount,
  //     booksList[9].pages,
  //     booksList[9].coverImgUrl,
  //     [],
  //     usersList[9],
  //   ),
  // ];
}
